### ISSUE TITLE
Error: Failed to parseField countryCode

### ISSUE THREAD

**Issue by R-D-P** [viruschidai/validate-vat#46]
Getting this error in the response.
There is also a soap message "soapMessage: '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><soap:Fault><faultcode>soap:Server</faultcode><faultstring>The given SOAPAction urn:ec.europa.eu:taxud:vies:services:checkVat/checkVat does not match an operation.</faultstring></soap:Fault></soap:Body></soap:Envelope>'"

**Comment by R-D-P** [comment]
I am using version "validate-vat": "^0.8.0"

**Comment by Retosi** [comment]
Are you sure, that you updated the package after changing the version to 0.8.0? I've gotten the same error recently and manually updated to 0.8 and it's working fine now. It got fixed in the .7 update.

After changing the package.json to the correct version, run npm i validate-vat -s again

**Comment by herkyl** [comment]
Any fixes for this? Getting the same error after upgrading to 0.8.0

**Comment by callezenwaka** [comment]
Any fix for this issue, still getting it with version 0.8.0.

**Comment by Retosi** [comment]
I have gotten the issue again later on with 0.8.0, we were able to upgrade to the typescript version of validate-vat (validate-vat-ts). So if you are using it in a Typescript project, I'd recommend changing. We did not experience any issues since

**Comment by callezenwaka** [comment]
Thanks @Retosi for the suggestion, unfortunately, we are not using typescript.

**Comment by thebillg** [comment]
try 0.9.0

**Comment by callezenwaka** [comment]
Thanks @thebillg, I have bumped it up to 0.9.0. Working perfectly now.
